databases:
  - name: emunahacademy-db
    databaseName: emunahacademy
    user: emunahacademy
    plan: starter

services:
  - type: web
    name: emunahacademy-api
    runtime: python
    plan: starter
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emunahacademy-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12"
